services:
  quartz:
    container_name: quartz
    image: ghcr.io/shipi1/quartz:latest
    expose:
      - "8080"
    volumes:
      - ${VAULT_PATH}:/usr/src/app/obsidian-vault
    restart: unless-stopped
    networks:
      - web

networks:
  web:
    external: true
